import Head from 'next/head'
import { Inter } from 'next/font/google'
import { useCallback, useState } from 'react'
import SettingsButton from '@/components/SettingsButton'
import Timer from '@/components/Timer'
import TimerSelect from '@/components/TimerSelect'
import TimerSettings from '@/components/TimerSettings'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  
  const [isSettingsOpen, setIsSettingsOpen] = useState(false)
  const [timer, setTimer] = useState('POMODORO')
  const [timersSeconds, setTimersSeconds] = useState({
    POMODORO: 25 * 60,
    SHORT_BREAK: 5 * 60,
    LONG_BREAK: 20 * 60,
  })

  const updateTimer = useCallback((newTimer) => () => {
    setTimer(newTimer)
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {
          isSettingsOpen ?
          <TimerSettings
            timersSeconds={timersSeconds}
            setTimersSeconds={setTimersSeconds}
            hideSettings={() => setIsSettingsOpen(false)}
          />
          :
          <>
            <div style={{ display: "flex", justifyContent: "right"}}>
              <SettingsButton
                showSettings={() => setIsSettingsOpen(true)}
              />
            </div>
            <Timer
              timer={timer}
              timersSeconds={timersSeconds}
            />
            <TimerSelect
              timer={timer}
              updateTimer={updateTimer}
            />
          </>
        }
      </main>
    </>
  )
}
