import Head from 'next/head'
import { Inter } from 'next/font/google'
import { useCallback, useState } from 'react'
import Timer from '@/components/Timer'
import TimerSelect from '@/components/TimerSelect'
import TimerConfig from '@/components/TimerConfig'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  
  const [timer, setTimer] = useState('POMODORO')
  const [timersSeconds, setTimersSeconds] = useState({
    POMODORO: 25 * 60,
    SHORT_BREAK: 5 * 60,
    LONG_BREAK: 20 * 60,
  })

  const updateTimer = useCallback((newTimer) => () => {
    setTimer(newTimer)
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <TimerConfig timersSeconds={timersSeconds} setTimersSeconds={setTimersSeconds}/>
        <Timer timer={timer} timersSeconds={timersSeconds}/>
        <TimerSelect timer={timer} updateTimer={updateTimer}/>
      </main>
    </>
  )
}
