import Head from 'next/head'
import { Inter } from 'next/font/google'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

/**
 * 
 * Home, it only containes the footer
 * @component
 */
export default function HomeLayout({ children }) {
  return (
    <>
      <Head>
        <title>NeuralClocks</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>
          { children }
          <Footer />
      </main>
    </>
  )
}